name: build macOS app

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller yt-dlp imageio-ffmpeg
    - name: build app
      run: pyinstaller --onefile --windowed --icon=assets/janinhx.icns --add-data 'assets:assets' ytdl.py
    - name: upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: yt-downloader-macos
        path: dist/ytdl.app